webtalk_init -webtalk_dir /home/jaroslav/Desktop/CTU_FIT/BI-SAP/lab5/lab5.sim/sim_1/behav/xsim/xsim.dir/l5_posloupnost_test_v2_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 10 12:45:24 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "77715673-e133-4302-83fe-6bd74b59227a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cebef4f7f8d641e9a17c1fdfc16358df" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 19.1 Tessa" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2367.060 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "19960 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "133152_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2540653171 -regid "" -xml /home/jaroslav/Desktop/CTU_FIT/BI-SAP/lab5/lab5.sim/sim_1/behav/xsim/xsim.dir/l5_posloupnost_test_v2_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jaroslav/Desktop/CTU_FIT/BI-SAP/lab5/lab5.sim/sim_1/behav/xsim/xsim.dir/l5_posloupnost_test_v2_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jaroslav/Desktop/CTU_FIT/BI-SAP/lab5/lab5.sim/sim_1/behav/xsim/xsim.dir/l5_posloupnost_test_v2_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
