#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Apr 10 12:25:42 CEST 2020
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto cebef4f7f8d641e9a17c1fdfc16358df --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot l5_posloupnost_test_v2_wrapper_behav xil_defaultlib.l5_posloupnost_test_v2_wrapper -log elaborate.log
